---
title: "Inverse Problem Setup"
author: "Andrew Roberts"
date: '2024-11-22'
output: html_document
---

```{r, echo = FALSE, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Settings
experiment_tag <- "vsem"

```

```{r, echo = FALSE, include = FALSE}
# Setup and filepaths
base_dir <- file.path("/projectnb", "dietzelab", "arober", "gp-calibration")
src_dir <- file.path(base_dir, "src")
output_dir <- file.path(base_dir, "output", "gp_post_approx_paper", 
                        experiment_tag, run_tag)

```




# Summary of Inverse Problem 
```{r}
load(file.path(output_dir, "inv_prob_list.RData"))
par_prior <- inv_prob$par_prior
```

## Prior Distribution
```{r}
print(inv_prob$par_info)

prior_plots <- plot_prior_samp(par_prior)
for(plt in prior_plots) plot(plt)
```

## Likelihood
```{r}
print(llik_obj_exact$lik_description)
print(paste0("Likelihood variance ground truth: ", inv_prob$sig2_true))
print(paste0("Likelihood variance model: ", llik_obj_exact$get_lik_par()[1]))
```

## Model Driver
```{r}
driver_plt <- ggplot(data.frame(t=inv_prob$time_points,PAR=inv_prob$driver)) + 
                     geom_point(aes(x=t,y=PAR)) + 
                     ggtitle("Model Driver (PAR)") + 
                     xlab("Day") + ylab("PAR")

plot(driver_plt)
```

## Ground truth observable vs. observations
```{r}
df_inv_prob_data <- data.frame(t=inv_prob$time_points, 
                               y_true=drop(inv_prob$y_true), 
                               y=drop(inv_prob$y))
plt_outputs <- ggplot(data=df_inv_prob_data) +
                      geom_point(aes(x=t, y=y), color="red") + 
                      geom_line(aes(x=t, y=y_true), color="black") + 
                      ylab("output") + ggtitle("True and Observed y")

plot(plt_outputs)
```

## Other model outputs
```{r}
# Plot other model outputs. 
df_model_outputs_true <- data.frame(inv_prob$model_output_true[1,,])
colnames(df_model_outputs_true) <- inv_prob$output_names
df_model_outputs_true$time <- inv_prob$time_points
for(output_var in inv_prob$output_names) {
  output_var <- sym(output_var)
  plt <- ggplot(df_model_outputs_true) + geom_line(aes(x=time,y=!!output_var)) + 
         ggtitle("Ground Truth Trajectory") + xlab("Days") + ylab(output_var)
  plot(plt)
}

```
# Inverse Problem Solution via Exact MCMC (no emulation)

## Exact log-likelihood, varying one parameter at a time. 
```{r}
plt_proj <- llik_obj_exact$plot_1d_projection(n_points=100, 
                                              input_bounds=t(inv_prob$par_prior[,c("param1","param2")]), 
                                              plot_type="llik")
for(plt in plt_proj) plot(plt)
```

## Exact MCMC
```{r}
samp_dt_exact <- fread(file.path(output_dir, "mcmc_samp_exact.csv"))

# MCMC Plots: exact. 
trace_plots_exact <- get_trace_plots(samp_dt_exact, test_labels="exact", 
                                     param_types="par",
                                     itr_start=burn_in_start)
hist_plots_exact <- get_hist_plot_comparisons(samp_dt_exact, test_labels="exact", 
                                              param_types="par", 
                                              itr_start=burn_in_start)
corr_plots_exact <- get_mcmc_2d_density_plots(samp_dt_exact, test_labels="exact", 
                                              itr_start=burn_in_start)$exact

for(plt in trace_plots_exact) plot(plt) 
for(plt in hist_plots_exact) plot(plt)
for(plt in corr_plots_exact) plot(plt)
```

# Gaussian process emulators

## Design information
```{r}
load(file.path(output_dir, "design_info.RData"))
load(file.path(output_dir, "test_info.RData"))

print("Initial design (training) data:")
print(paste0("Number design points: ", design_info$N_design))
print(paste0("Design method: ", design_info$design_method))

print("Validation data:")
print(paste0("Number validation points: ", test_info$N_design))
print(paste0("Validation point sampling method: ", test_info$design_method))
```