---
title: "Plots for NESS Student Symposium"
author: "Andrew Roberts"
date: '2024-04-15'
output: html_document
---

```{r, echo = FALSE, include = FALSE}
#
# Generating plots/figures for 2024 New England Student Symposium talk. 
# Goals: 
#    (1) 1d illustrative example for different posterior approximations. 
#    (2) 2d illustrative example of posterior approximations and sequential design. 
#    (3) Higher-dimensional example showing posterior contractions. 

knitr::opts_chunk$set(echo = FALSE)

library(lhs)
library(ggplot2)
library(viridis)
library(parallel)
library(gridExtra)
library(data.table)

base_dir <- getwd()
src_dir <- file.path(base_dir, "src")
ness_output_dir <- file.path(base_dir, "output", "NESS2024_plots")

source(file.path(src_dir, "gpWrapper.r"))
source(file.path(src_dir, "general_helper_functions.r"))
source(file.path(src_dir, "statistical_helper_functions.r"))
source(file.path(src_dir, "plotting_helper_functions.r"))
source(file.path(src_dir, "llikEmulator.r"))
source(file.path(src_dir, "gp_emulator_functions.r"))
source(file.path(src_dir, "sim_study_functions.r"))
source(file.path(src_dir, "mcmc_calibration_functions.r"))
source(file.path(src_dir, "seq_design_gp.r"))
source(file.path(src_dir, "seq_design.r"))
source(file.path(src_dir, "gp_mcmc_functions.r"))
```


# Part 1: One-Dimensional Example
```{r}
seed_pt1 <- 1
set.seed(seed_pt1)

# Define inverse problem. 
N_obs <- 20
fwd_model <- function(u) exp(u) + cos(2*u)
par_prior_params <- data.frame(dist="Gaussian", param1=1, param2=1)
rownames(par_prior_params) <- "u"
u_true <- 1.0
sig2_true <- 1
y <- fwd_model(rep(u_true, N_obs)) + sqrt(sig2_true) * rnorm(N_obs)

default_conditional <- TRUE
default_normalize <- FALSE
llik_exact <- llikEmulatorExactGaussDiag(llik_lbl="exact", fwd_model=fwd_model, 
                                         y_obs=y, dim_par=1L, use_fixed_lik_par=TRUE,
                                         sig2=sig2_true, par_names=rownames(par_prior_params), 
                                         default_conditional=default_conditional, 
                                         default_normalize=default_normalize)
inv_prob1 <- list(llik=llik_exact, par_prior=par_prior_params, y=y, par_true=u_true, sig2_true=sig2_true)

# Create grid for plotting. 
N_grid <- 101
u_grid <- get_tensor_product_grid(N_grid, inv_prob1$par_prior)
test_info <- list(inputs=u_grid)
test_info$outputs <- llik_exact$assemble_llik(test_info$inputs)
test_info$lprior <- calc_lprior_theta(test_info$inputs, inv_prob1$par_prior)
test_info$lpost <- test_info$outputs + test_info$lprior

# Plot true unnormalized posterior density. 
plot(test_info$inputs, exp(test_info$lpost), type="l", main="True unnormalized posterior density", xlab="u", ylab="density")
plot(test_info$inputs, test_info$outputs, type="l", main="True unnormalized log-likelihood", xlab="u", ylab="density")
```

```{r}
# Initial design. 
N_design <- 5
design_info <- list()
design_info$inputs <- get_batch_design("LHS", N_design, prior_params=inv_prob1$par_prior) # "tensor_product_grid"
design_info$outputs <- llik_exact$assemble_llik(design_info$inputs)
design_info$lprior <- calc_lprior_theta(design_info$inputs, inv_prob1$par_prior)
design_info$lpost <- design_info$outputs + design_info$lprior

# Fit GP to log-likelihood. 
gp <- gpWrapperHet(design_info$inputs, matrix(design_info$outputs, ncol=1), normalize_output=TRUE, scale_input=TRUE)
gp$fit("Gaussian", "constant", estimate_nugget=FALSE)
llik_gp <- llikEmulatorGP("llik_gp", gp, default_conditional=default_conditional, 
                          default_normalize=default_normalize, lik_par=inv_prob1$sig2_true)
llik_gp$plot_llik_pred_1d(test_info$inputs, include_CI=TRUE, true_llik=test_info$outputs)

# Truncate the prior based on the design points, allowing a small amount of extrapolation. 
extrapolation_radius <- 0.2
prior_bounds <- gp$X_bounds
prior_bounds[1,] <- prior_bounds[1,] - extrapolation_radius
prior_bounds[2,] <- prior_bounds[2,] + extrapolation_radius
inv_prob1$par_prior_trunc <- truncate_prior_theta(inv_prob1$par_prior, prior_bounds)

input_trunc_idx <- (test_info$inputs >= prior_bounds[1,]) & (test_info$inputs <= prior_bounds[2,])
test_info_trunc <- list()
test_info_trunc$inputs <- test_info$inputs[input_trunc_idx,, drop=FALSE]
test_info_trunc$outputs <- test_info$outputs[input_trunc_idx]
test_info_trunc$lprior_trunc <- test_info$lprior[input_trunc_idx]                                             
test_info_trunc$lpost_trunc <- test_info$lpost[input_trunc_idx]

# Save plot. 
gp_plot <- llik_gp$plot_llik_pred_1d(test_info$inputs, include_CI=TRUE, true_llik=test_info$outputs)
gp_plot <- gp_plot + xlim(-1.5, 3) + ylim(-4000, 200) + ylab("log-likelihood")

plot(gp_plot)

ggsave(file.path(ness_output_dir, "gp_plot.png"), gp_plot)

```


```{r}
# Comparing mean and marginal approximations. 
llik_pred <- llik_gp$predict(test_info_trunc$inputs)
log_post_mean <- gp_lpost_mean(test_info_trunc$inputs, llik_gp, 
                               par_prior_params, llik_pred_list=llik_pred)
log_post_marg <- gp_lpost_marginal(test_info_trunc$inputs, llik_gp, 
                                   par_prior_params, llik_pred_list=llik_pred)
df_post_dens_approx <- data.frame(inputs=test_info_trunc$inputs[,1], exact=test_info_trunc$lpost, 
                                  approx_mean=log_post_mean, approx_marg=log_post_marg)
df_design <- data.frame(inputs=design_info$inputs[,1], lpost=design_info$lpost)

approx_log_dens_plt <- ggplot(df_post_dens_approx) + 
                          geom_line(aes(x=inputs, y=exact), color="black") + 
                          geom_line(aes(x=inputs, y=approx_mean), color="blue") + 
                          geom_line(aes(x=inputs, y=approx_marg), color="red") + 
                          geom_point(aes(x=inputs, y=lpost), data=df_design, color="black") + 
                          xlab("u") + ylab("log density") + ggtitle("Unnormalized log posterior approx")


approx_dens_plt <- ggplot(df_post_dens_approx) + 
                    geom_line(aes(x=inputs, y=exp(exact)), color="black") + 
                    geom_line(aes(x=inputs, y=exp(approx_mean)), color="blue") + 
                    geom_line(aes(x=inputs, y=exp(approx_marg)), color="red") +
                    geom_point(aes(x=inputs, y=exp(lpost)), data=df_design, color="black") + 
                    xlab("u") + ylab("density") + ggtitle("Unnormalized posterior approx")

plot(approx_log_dens_plt)
plot(approx_dens_plt)
```


```{r}
# Noisy MCMC approximations. 

# TODO: In mcmc_gp_noisy, get rid of mention of "SSR". 
# I believe the results from before basically reflected the fact that the uncertainty in the GP was essentially uniform, so 
# the posterior reflected the prior Gaussian distribution. Also, I have not been truncating the prior based on the 
# design points; I should probably do this. 

N_mcmc <- 50000
mcmc_par_init <- sample_prior_theta(inv_prob1$par_prior_trunc)

mcmh_nocov_list <- mcmc_gp_noisy(llik_gp, inv_prob1$par_prior_trunc, N_itr=N_mcmc, mode="MCMH", 
                                 use_gp_cov=FALSE, par_init=mcmc_par_init)  
mcmh_cov_list <- mcmc_gp_noisy(llik_gp, inv_prob1$par_prior_trunc, N_itr=N_mcmc, mode="MCMH", 
                               use_gp_cov=TRUE, par_init=mcmc_par_init)                     
samp_dt <- format_mcmc_output(mcmh_nocov_list, test_label="nocov")
samp_dt <- append_mcmc_output(samp_dt, mcmh_cov_list, test_label="cov")

trace_plots <- get_trace_plots(samp_dt) 
for(plt in trace_plots) plot(plt) 
burn_in_start <- N_mcmc/2

get_hist_plot_comparisons(samp_dt, burn_in_start=burn_in_start, test_label_baseline="nocov")[[1]]
```

```{r}
# MCMC deterministic approximations. 

mcmc_list_marg <- mcmc_gp_deterministic_approx(llik_gp, inv_prob1$par_prior_trunc, par_init=mcmc_par_init, 
                                               N_itr=N_mcmc, approx_type="marginal")
mcmc_list_mean <- mcmc_gp_deterministic_approx(llik_gp, inv_prob1$par_prior_trunc, par_init=mcmc_par_init, 
                                               N_itr=N_mcmc, approx_type="mean")

samp_dt <- append_mcmc_output(samp_dt, mcmc_list_marg, test_label="marginal")
samp_dt <- append_mcmc_output(samp_dt, mcmc_list_mean, test_label="mean")

get_trace_plots(samp_dt, burn_in_start, test_labels=c("marginal", "mean"))

```



```{r}
# Exact samples, using original and truncated prior. 

exact_mcmc_test<- mcmc_gp_noisy(llik_exact, inv_prob1$par_prior, N_itr=N_mcmc, mode="MCMH", 
                                use_gp_cov=FALSE, par_init=mcmc_par_init)
exact_mcmc_test_trunc_prior <- mcmc_gp_noisy(llik_exact, inv_prob1$par_prior_trunc, N_itr=N_mcmc, mode="MCMH", 
                                             use_gp_cov=FALSE, par_init=mcmc_par_init)

samp_dt <- append_mcmc_output(samp_dt, exact_mcmc_test, test_label="exact")
samp_dt <- append_mcmc_output(samp_dt, exact_mcmc_test_trunc_prior, test_label="exact_trunc_prior")

get_trace_plots(samp_dt, burn_in_start, test_labels=c("exact", "exact_trunc_prior"))
get_hist_plot_comparisons(samp_dt, burn_in_start=burn_in_start, test_labels="exact_trunc_prior", 
                          test_label_baseline="exact")
```

```{r}
# Compare samples. 

get_hist_plot_comparisons(samp_dt, burn_in_start=burn_in_start, test_labels=c("marginal", "mean", "cov", "nocov"), 
                          test_label_baseline="exact")
```

# Part 2: Two-Dimensional Example
```{r, include = FALSE}
# VSEM model with 2d input space, restricting test case 4 to a single output. 
vsem_info <- generate_vsem_test_case(4)
vsem_info$output_vars <- "NEE"

vsem_info$ref_pars[vsem_info$pars_cal_sel,]

inv_prob2 <- list()
inv_prob2$fwd <- function(input) run_VSEM_single_input(input, computer_model_data=vsem_info)
inv_prob2$sig2_true <- diag(vsem_info$Sig_eps)[vsem_info$output_vars]
inv_prob2$par_true <- vsem_info$theta_true

# Prior distribution. 
inv_prob2$par_prior <- data.frame(dist=c("Uniform", "Uniform"), 
                                  param1=c(1.4, 0.45),
                                  param2=c(1.6, 0.55))
rownames(inv_prob2$par_prior) <- vsem_info$pars_cal_names

# Exact log likelihood. 
inv_prob2$llik <- llikEmulatorExactGaussDiag(llik_lbl="exact", fwd_model=inv_prob2$fwd, 
                                             y_obs=vsem_info$data_obs[,vsem_info$output_vars], 
                                             dim_par=length(inv_prob2$par_true), 
                                             use_fixed_lik_par=TRUE,
                                             sig2=inv_prob2$sig2_true, 
                                             par_names=vsem_info$pars_cal_names, 
                                             default_conditional=default_conditional, 
                                             default_normalize=default_normalize)


# Plot grounbd truth and observations. 
for(output_var in vsem_info$output_vars) {
 plotTimeSeries(observed=vsem_info$data_obs[, output_var],
                predicted=vsem_info$data_ref[, output_var], main=output_var) 
}

```

```{r}
# Define design points and test grid. 

# Initial design.
inv_prob2$design_info <- list(N_design=8)
inv_prob2$design_info$inputs <- get_batch_design("LHS", inv_prob2$design_info$N_design, 
                                                 prior_params=inv_prob2$par_prior)
inv_prob2$design_info$outputs <- inv_prob2$llik$assemble_llik(inv_prob2$design_info$inputs)
inv_prob2$design_info$lprior <- calc_lprior_theta(inv_prob2$design_info$inputs, inv_prob2$par_prior)
inv_prob2$design_info$lpost <- inv_prob2$design_info$outputs + inv_prob2$design_info$lprior

# Test grid. 
inv_prob2$test_info <- list(N_design=51^2)
inv_prob2$test_info$inputs <- get_batch_design("tensor_product_grid", inv_prob2$test_info$N_design, 
                                               prior_params=inv_prob2$par_prior)
inv_prob2$test_info$outputs <- inv_prob2$llik$assemble_llik(inv_prob2$test_info$inputs)
inv_prob2$test_info$lprior <- calc_lprior_theta(inv_prob2$test_info$inputs, inv_prob2$par_prior)
inv_prob2$test_info$lpost <- inv_prob2$test_info$outputs + inv_prob2$test_info$lprior

```

```{r}
# Plot true likelihood with design points. 

post_heatmap <- plot_heatmap(inv_prob2$test_info$inputs, exp(inv_prob2$test_info$lpost + 1800), 
                             points_mat=inv_prob2$design_info$inputs,  
                             raster=TRUE, point_coords=inv_prob2$par_true, 
                             main_title="Posterior, Initial Design", 
                             legend_label="unnormalized density", points_mat_lab="Initial design",
                             xlab=inv_prob2$llik$input_names[1], ylab=inv_prob2$llik$input_names[2], 
                             points_mat_size=3, point_coords_size=3)

lpost_heatmap <- plot_heatmap(inv_prob2$test_info$inputs, inv_prob2$test_info$lpost, 
                             points_mat=inv_prob2$design_info$inputs,  
                             raster=TRUE, point_coords=inv_prob2$par_true, 
                             main_title="Log-posterior, Initial Design", 
                             legend_label="log density", points_mat_lab="Initial design",
                             xlab=inv_prob2$llik$input_names[1], ylab=inv_prob2$llik$input_names[2],
                             points_mat_size=3, point_coords_size=3)

plot(post_heatmap)
plot(lpost_heatmap)

llik_true_save <- lpost_heatmap + xlab("u1") + ylab("u2") + 
                        theme(legend.position = "none", 
                              axis.text.x=element_blank(),
                              axis.ticks.x=element_blank(), axis.text.y=element_blank(), 
                              axis.ticks.y=element_blank(),
                              panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
                              panel.border = element_blank(), panel.background = element_blank(),
                              plot.background = element_blank(), 
                              axis.title=element_text(size=22), 
                              plot.title=element_text(size=35))
                              
post_true_save <- post_heatmap + xlab("u1") + ylab("u2") + 
                        theme(legend.position = "none", 
                              axis.text.x=element_blank(),
                              axis.ticks.x=element_blank(), axis.text.y=element_blank(), 
                              axis.ticks.y=element_blank(),
                              panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
                              panel.border = element_blank(), panel.background = element_blank(),
                              plot.background = element_blank(), 
                              axis.title=element_text(size=22), 
                              plot.title=element_text(size=35))

ggsave(file.path(ness_output_dir, "llik_true.png"), llik_true_save)
ggsave(file.path(ness_output_dir, "post_true.png"), post_true_save)


```

```{r}
# Fit emulator directly to log-likelihood. 
# NOTE: not truncating prior in this example, since the uniform prior esssentially already does this. 

# Fit GP to log-likelihood. 
inv_prob2$gp <- gpWrapperHet(inv_prob2$design_info$inputs, matrix(inv_prob2$design_info$outputs, ncol=1), 
                             normalize_output=TRUE, scale_input=TRUE)
inv_prob2$gp$fit("Gaussian", "constant", estimate_nugget=FALSE)

# Create llikEmulator object. 
inv_prob2$llik_gp <- llikEmulatorGP("llik_gp", inv_prob2$gp, default_conditional=default_conditional, 
                                    default_normalize=default_normalize, lik_par=inv_prob2$sig2_true)
```


```{r}
# Plots for initial GP fit. 

llik_pred_list <- inv_prob2$llik_gp$predict(inv_prob2$test_info$inputs)


llik_pred_mean_heatmap <- plot_heatmap(inv_prob2$test_info$inputs, llik_pred_list$mean, 
                                       points_mat=inv_prob2$design_info$inputs,  
                                       raster=TRUE, point_coords=inv_prob2$par_true, 
                                       main_title="Predictive Mean", 
                                       legend_label="GP Mean", points_mat_lab="Initial design",
                                       xlab=inv_prob2$llik$input_names[1], ylab=inv_prob2$llik$input_names[2], 
                                       points_mat_size=3, point_coords_size=3)
llik_pred_sd_heatmap <- plot_heatmap(inv_prob2$test_info$inputs, sqrt(llik_pred_list$var), 
                                     points_mat=inv_prob2$design_info$inputs,  
                                     raster=TRUE, point_coords=inv_prob2$par_true, 
                                     main_title="Predictive SD", 
                                     legend_label="GP SD", points_mat_lab="Initial design",
                                     xlab=inv_prob2$llik$input_names[1], ylab=inv_prob2$llik$input_names[2], 
                                     points_mat_size=3, point_coords_size=3)

plot(llik_pred_mean_heatmap)
plot(llik_pred_sd_heatmap)



llik_pred_mean_save <- llik_pred_mean_heatmap + xlab("u1") + ylab("u2") + 
                        theme(legend.position = "none", 
                              axis.text.x=element_blank(),
                              axis.ticks.x=element_blank(), 
                              axis.text.y=element_blank(), 
                              axis.ticks.y=element_blank(),
                              panel.grid.major = element_blank(), 
                              panel.grid.minor = element_blank(),
                              panel.border = element_blank(), 
                              panel.background = element_blank(),
                              plot.background = element_blank(), 
                              axis.title=element_text(size=22), 
                              plot.title=element_text(size=35)) 
                        

llik_pred_sd_save <- llik_pred_sd_heatmap + xlab("u1") + ylab("u2") + 
                        theme(legend.position = "none", axis.text.x=element_blank(),
                              axis.ticks.x=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank(),
                              panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
                              panel.border = element_blank(), panel.background = element_blank(),
                              plot.background = element_blank(), 
                              axis.title=element_text(size=22), 
                              plot.title=element_text(size=35)) 

ggsave(file.path(ness_output_dir, "llik_pred_mean.png"), llik_pred_mean_save)
ggsave(file.path(ness_output_dir, "llik_pred_sd.png"), llik_pred_sd_save)


```

```{r}
# Compute deterministic posterior approximations. 


lik_pred_mean_heatmap <- plot_heatmap(inv_prob2$test_info$inputs, exp(llik_pred_list$mean + 1800), 
                                      points_mat=inv_prob2$design_info$inputs,  
                                      raster=TRUE, point_coords=inv_prob2$par_true, 
                                      main_title="Exponentiated llik Predictive Mean", 
                                      legend_label="exp(GP Mean + cst)", points_mat_lab="Initial design",
                                      xlab=inv_prob2$llik$input_names[1], ylab=inv_prob2$llik$input_names[2])


```


```{r}
# Run sampling algorithms. 
inv_prob2$mcmc <- list(N_mcmc=50000, par_init=sample_prior_theta(inv_prob2$par_prior))


mcmc_exact<- mcmc_gp_noisy(inv_prob2$llik, inv_prob2$par_prior, N_itr=inv_prob2$mcmc$N_mcmc, 
                           mode="MCMH", use_gp_cov=FALSE, par_init=inv_prob2$mcmc$par_init)
mcmc_noisy_cov <- mcmc_gp_noisy(inv_prob2$llik_gp, inv_prob2$par_prior, N_itr=inv_prob2$mcmc$N_mcmc,  
                                 mode="MCMH", use_gp_cov=TRUE, par_init=inv_prob2$mcmc$par_init)
mcmc_noisy_nocov <- mcmc_gp_noisy(inv_prob2$llik_gp, inv_prob2$par_prior, N_itr=inv_prob2$mcmc$N_mcmc,  
                                  mode="MCMH", use_gp_cov=FALSE, par_init=inv_prob2$mcmc$par_init)
mcmc_marginal <- mcmc_gp_deterministic_approx(inv_prob2$llik_gp, inv_prob2$par_prior, 
                                              par_init=inv_prob2$mcmc$par_init, N_itr=inv_prob2$mcmc$N_mcmc,
                                              approx_type="marginal")
mcmc_mean <- mcmc_gp_deterministic_approx(inv_prob2$llik_gp, inv_prob2$par_prior, 
                                          par_init=inv_prob2$mcmc$par_init, N_itr=inv_prob2$mcmc$N_mcmc,
                                          approx_type="mean")

# TODO: should allow multiple samples to be passed in, which a character vector of test labels. 
samp_dt2 <- format_mcmc_output(mcmc_exact, "exact")
samp_dt2 <- append_mcmc_output(samp_dt2, mcmc_noisy_cov, "mcwm_cov")
samp_dt2 <- append_mcmc_output(samp_dt2, mcmc_noisy_nocov, "mcwm_nocov")
samp_dt2 <- append_mcmc_output(samp_dt2, mcmc_marginal, "marginal")
samp_dt2 <- append_mcmc_output(samp_dt2, mcmc_mean, "mean")

# TODO: update these funtions so that they optionally have multiple plots in a single plot object.  
get_trace_plots(samp_dt2)
get_hist_plot_comparisons(samp_dt2, burn_in_start=0.5*inv_prob2$mcmc$N_mcmc, test_label_baseline="exact")

# TODO: update this function: get_2d_density_contour_plot()

```

```{r}
# 2d Density contour plots 
samp_dt2_wide <- data.table::dcast(select_mcmc_samp(samp_dt2, burn_in_start=0.5*inv_prob2$mcmc$N_mcmc), 
                                   formula="param_type+itr+test_label ~ param_name", 
                                   value.var="sample")

kde_2d_plt <- ggplot(samp_dt2_wide[test_label != "mcwm_nocov"]) +
                geom_density_2d(aes(x=LAR, y=KEXT), contour_var="ndensity") + 
                geom_point(aes(x=LAR, y=KEXT), data=as.data.frame(inv_prob2$design_info$inputs), color="red") + 
                facet_wrap(vars(test_label)) + 
                xlab("u1") + ylab("u2") + ggtitle("Posterior Predictions") + 
                theme(axis.title=element_text(size=22), 
                              plot.title=element_text(size=35))


                              


ggsave(file.path(ness_output_dir, "kde_contour_plots.png"), kde_2d_plt)

plot(kde_2d_plt)
```


```{r}
# Sequential design. 

llik_true <- function(input) {
  
    sig2_val <- inv_prob2$sig2_true
    y <- vsem_info$data_obs[,vsem_info$output_vars]
    N_obs <- vsem_info$n_obs
  
    # Construct log likelihood. 
    llik <- -0.5 * sum((y - inv_prob2$fwd(input))^2 / sig2_val, na.rm=TRUE)
    if(default_normalize || !default_conditional) llik <- llik - 0.5 * sum(log(sig2_val))
    if(default_normalize) llik <- llik - 0.5*N_obs*log(2*pi)

    return(drop(llik))
}
  

N_grid_points <- 300
grid_points_idx <- sample.int(nrow(inv_prob2$test_info$inputs), size=N_grid_points)

results <- acquire_batch_input_sequentially(inv_prob2$gp, "IEVAR_grid", N_batch=20, model_response_heuristic="none", 
                                            opt_method="grid", f_exact=llik_true, reoptimize_hyperpar=FALSE, 
                                            grid_points=inv_prob2$test_info$inputs[grid_points_idx,], 
                                            candidate_grid=inv_prob2$test_info$inputs[grid_points_idx,])


```

```{r}
df_acq_points <- data.frame(results$input_batch)
colnames(df_acq_points) <- c("u1", "u2")
df_acq_points$order <- 1:nrow(df_acq_points)


plt_acq <- post_true_save + geom_text(data=df_acq_points, mapping=aes(x=u1, y=u2, label=order, size=3), 
                                      color="red") + ggtitle("Sequential Design")
plot(plt_acq)   

ggsave(file.path(ness_output_dir, "seq_design_plot.png"), plt_acq)


```



