---
title: "Posterior Approximation Comparison"
author: "Andrew Roberts"
date: '2024-05-02'
output: html_document
---

```{r, echo = FALSE, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(lhs)
library(ggplot2)
library(viridis)
library(parallel)
library(gridExtra)
library(data.table)

base_dir <- getwd()
src_dir <- file.path(base_dir, "src")
ness_output_dir <- file.path(base_dir, "output", "NESS2024_plots")

source(file.path(src_dir, "gpWrapper.r"))
source(file.path(src_dir, "general_helper_functions.r"))
source(file.path(src_dir, "statistical_helper_functions.r"))
source(file.path(src_dir, "plotting_helper_functions.r"))
source(file.path(src_dir, "llikEmulator.r"))
source(file.path(src_dir, "gp_emulator_functions.r"))
source(file.path(src_dir, "sim_study_functions.r"))
source(file.path(src_dir, "mcmc_calibration_functions.r"))
source(file.path(src_dir, "seq_design_gp.r"))
source(file.path(src_dir, "seq_design.r"))
source(file.path(src_dir, "gp_mcmc_functions.r"))
```


# Part 1: One-Dimensional Example
```{r}
seed_pt1 <- 1
set.seed(seed_pt1)

# Define inverse problem. 
N_obs <- 20
fwd_model <- function(u) exp(u) + cos(2*u)
par_prior_params <- data.frame(dist="Gaussian", param1=1, param2=1)
rownames(par_prior_params) <- "u"
u_true <- 1.0
sig2_true <- 1
y <- fwd_model(rep(u_true, N_obs)) + sqrt(sig2_true) * rnorm(N_obs)

default_conditional <- TRUE
default_normalize <- FALSE
llik_exact <- llikEmulatorExactGaussDiag(llik_lbl="exact", fwd_model=fwd_model, 
                                         y_obs=y, dim_par=1L, use_fixed_lik_par=TRUE,
                                         sig2=sig2_true, par_names=rownames(par_prior_params), 
                                         default_conditional=default_conditional, 
                                         default_normalize=default_normalize)
inv_prob1 <- list(llik=llik_exact, par_prior=par_prior_params, y=y, par_true=u_true, sig2_true=sig2_true)

# Create grid for plotting. 
N_grid <- 101
u_grid <- get_tensor_product_grid(N_grid, inv_prob1$par_prior)
test_info <- list(inputs=u_grid)
test_info$outputs <- llik_exact$assemble_llik(test_info$inputs)
test_info$lprior <- calc_lprior_theta(test_info$inputs, inv_prob1$par_prior)
test_info$lpost <- test_info$outputs + test_info$lprior

# Plot true unnormalized posterior density. 
plot(test_info$inputs, exp(test_info$lpost), type="l", main="True unnormalized posterior density", xlab="u", ylab="density")
plot(test_info$inputs, test_info$outputs, type="l", main="True unnormalized log-likelihood", xlab="u", ylab="density")
```

```{r}
# Initial design. 
N_design <- 5
design_info <- list()
design_info$inputs <- get_batch_design("LHS", N_design, prior_params=inv_prob1$par_prior) # "tensor_product_grid"
design_info$outputs <- llik_exact$assemble_llik(design_info$inputs)
design_info$lprior <- calc_lprior_theta(design_info$inputs, inv_prob1$par_prior)
design_info$lpost <- design_info$outputs + design_info$lprior

# Fit GP to log-likelihood. 
gp <- gpWrapperHet(design_info$inputs, matrix(design_info$outputs, ncol=1), normalize_output=TRUE, scale_input=TRUE)
gp$fit("Gaussian", "constant", estimate_nugget=FALSE)
llik_gp <- llikEmulatorGP("llik_gp", gp, default_conditional=default_conditional, 
                          default_normalize=default_normalize, lik_par=inv_prob1$sig2_true)
llik_gp$plot_llik_pred_1d(test_info$inputs, include_CI=TRUE, true_llik=test_info$outputs)

# Truncate the prior based on the design points, allowing a small amount of extrapolation. 
extrapolation_radius <- 0.2
prior_bounds <- gp$X_bounds
prior_bounds[1,] <- prior_bounds[1,] - extrapolation_radius
prior_bounds[2,] <- prior_bounds[2,] + extrapolation_radius
inv_prob1$par_prior_trunc <- truncate_prior_theta(inv_prob1$par_prior, prior_bounds)

input_trunc_idx <- (test_info$inputs >= prior_bounds[1,]) & (test_info$inputs <= prior_bounds[2,])
test_info_trunc <- list()
test_info_trunc$inputs <- test_info$inputs[input_trunc_idx,, drop=FALSE]
test_info_trunc$outputs <- test_info$outputs[input_trunc_idx]
test_info_trunc$lprior_trunc <- test_info$lprior[input_trunc_idx]                                             
test_info_trunc$lpost_trunc <- test_info$lpost[input_trunc_idx]

# Save plot. 
gp_plot <- llik_gp$plot_llik_pred_1d(test_info$inputs, include_CI=TRUE, true_llik=test_info$outputs)
gp_plot <- gp_plot + xlim(-1.5, 3) + ylim(-4000, 200) + ylab("log-likelihood")

plot(gp_plot)


```


```{r}
# Compare MCWMH-Joint and marginal-acc-prob-joint distributions, which in theory should sample from 
# the same distribution. 
# TODO: update the llikEmulator class so that the predictive mean/var are always returned as 
#       vectors/not matrices and the cov is returned as a matrix. 

N_mcmc <- 50000
mcmc_par_init <- sample_prior_theta(inv_prob1$par_prior_trunc)

# MCWMH-Joint. 
mcmh_cov_list <- mcmc_gp_noisy(llik_gp, inv_prob1$par_prior_trunc, N_itr=N_mcmc, mode="MCMH", 
                               use_gp_cov=TRUE, par_init=mcmc_par_init) 
samp_dt <- format_mcmc_output(mcmh_cov_list, test_label="mcwmh-joint")

# marginal-acc-prob-joint. 
marg_acc_joint_list <- mcmc_gp_acc_prob_approx(llik_gp, inv_prob1$par_prior_trunc, par_init=mcmc_par_init, 
                                               N_itr=N_mcmc, approx_type="joint-marginal")
samp_dt <- append_mcmc_output(samp_dt, marg_acc_joint_list, test_label="acc-marg-joint")

# Exact. 
exact_mcmc_list<- mcmc_gp_noisy(llik_exact, inv_prob1$par_prior, N_itr=N_mcmc, mode="MCMH", 
                                use_gp_cov=FALSE, par_init=mcmc_par_init)
samp_dt <- append_mcmc_output(samp_dt, exact_mcmc_list, test_label="exact")
```


```{r}
burn_in_start <- N_mcmc/2
trace_plots <- get_trace_plots(samp_dt, burn_in_start=burn_in_start) 
hist_plots <- get_hist_plot_comparisons(samp_dt, burn_in_start=burn_in_start, test_label_baseline="mcwmh-joint")

for(plt in trace_plots) plot(plt) 
for(plt in hist_plots) plot(plt)
```


