---
title: "VSEM Example"
author: "Andrew Roberts"
date: '2024-09-10'
output: html_document
---
```{r, echo = FALSE, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(lhs)
library(ggplot2)
library(viridis)
library(parallel)
library(gridExtra)
library(data.table)

experiment_tag <- "vsem"
run_tag <- "6d_N140_LHS"
base_dir <- file.path("/projectnb", "dietzelab", "arober", "gp-calibration")
src_dir <- file.path(base_dir, "src")
output_dir <- file.path(base_dir, "output", "gp_post_approx_paper", 
                        experiment_tag, run_tag)

source(file.path(src_dir, "gpWrapper.r"))
source(file.path(src_dir, "general_helper_functions.r"))
source(file.path(src_dir, "gp_helper_functions.r"))
source(file.path(src_dir, "statistical_helper_functions.r"))
source(file.path(src_dir, "inv_prob_test_functions.r"))
source(file.path(src_dir, "plotting_helper_functions.r"))
source(file.path(src_dir, "mcmc_helper_functions.r"))
source(file.path(src_dir, "llikEmulator.r"))
source(file.path(src_dir, "gp_emulator_functions.r"))
source(file.path(src_dir, "sim_study_functions.r"))
source(file.path(src_dir, "mcmc_calibration_functions.r"))
source(file.path(src_dir, "seq_design_gp.r"))
source(file.path(src_dir, "seq_design.r"))
source(file.path(src_dir, "gp_mcmc_functions.r"))

# Plot settings applied to all plots. 
design_pt_size <- 4
line_thickness <- 1.5
design_color <- "red"
xlim <- c(-10, 10)
ylim <- c(0.0777, 0.4)

# Settings for MCMC plotting. 
burn_in_start <- 100000L

# Settings for confidence intervals displayed in plots. 
interval_method <- "pm_std_dev"
N_std_dev <- 1.64
```

# Summary of Inverse Problem 

```{r}
#
# Plot model driver.  
#

load(file.path(output_dir, "inv_prob_list.RData"))

driver_plt <- ggplot(data.frame(t=inv_prob$time_points,PAR=inv_prob$driver)) + 
                     geom_point(aes(x=t,y=PAR)) + 
                     ggtitle("Model Driver (PAR)") + 
                     xlab("Day") + ylab("PAR")

plot(driver_plt)
```


```{r}
#
# Plot true observable vs. observations.  
#

df_inv_prob_data <- data.frame(t=inv_prob$time_points, y_true=drop(inv_prob$y_true), 
                               y=drop(inv_prob$y))
plt_outputs <- ggplot(data=df_inv_prob_data) +
                      geom_point(aes(x=t, y=y), color="red") + 
                      geom_line(aes(x=t, y=y_true), color="black") + 
                      ylab("output") + ggtitle("True and Observed y")

plot(plt_outputs)
```

```{r}
# Plot other model outputs. 

df_model_outputs_true <- data.frame(inv_prob$model_output_true[1,,])
colnames(df_model_outputs_true) <- inv_prob$output_names
df_model_outputs_true$time <- inv_prob$time_points
for(output_var in inv_prob$output_names) {
  output_var <- sym(output_var)
  plt <- ggplot(df_model_outputs_true) + geom_line(aes(x=time,y=!!output_var)) + 
         ggtitle("Ground Truth Trajectory") + xlab("Days") + ylab(output_var)
  plot(plt)
}

```

```{r}
# Info on parameters. 
inv_prob$par_info

# Prior plots.
prior_plots <- plot_prior_samp(inv_prob$par_prior)
for(plt in prior_plots) plot(plt)
```

```{r}
# Info on likelihood. 

print(paste0("Likelihood SD true: ", sqrt(inv_prob$sig2_true)))
print(paste0("Likelihood SD model: ", sqrt(inv_prob$sig2_model)))
```


```{r}
# Print settings. 

load(file.path(output_dir, "design_info.RData"))

print("Settings:")
print(paste0("Parameter space dimension: ", nrow(inv_prob$par_prior)))
print(paste0("Number design points: ", design_info$N_design))
print(paste0("Design method: ", design_info$design_method))

print("Priors and true parameter:")
inv_prob$par_prior$par_true <- inv_prob$par_true
print(inv_prob$par_prior)
```


# Investigating exact log-likelihood, varying one parameter at a time. 
```{r}
llik_exact <- inv_prob$llik_obj
plt_proj <- llik_exact$plot_1d_projection(n_points=100, 
                                          input_bounds=t(inv_prob$par_prior[,c("param1","param2")]), 
                                          plot_type="llik")

for(plt in plt_proj) plot(plt)
```

```{r}
# Looking into what's going on with "Cv" parameter. 
random_idx <- sample(1:nrow(test_info$input), 10)

for(i in random_idx) {
  plt_proj <- llik_exact$plot_1d_projection(n_points=100, input_names_proj="Cv",  
                                            input_fixed=test_info$input[i,,drop=FALSE], 
                                            input_bounds=t(inv_prob$par_prior[,c("param1","param2")]), 
                                            plot_type="llik")
  plot(plt_proj[["Cv"]])
}

```


# Inverse Problem Solution via Exact MCMC (no emulation)
```{r}
#
# MCMC Plots: exact.  
#

samp_dt <- fread(file.path(output_dir, "mcmc_samp.csv"))

# MCMC Plots: exact. 
trace_plots_exact <- get_trace_plots(samp_dt, test_label="exact", param_types="par",
                                     param_names=inv_prob$par_names, itr_start=burn_in_start)
hist_plots_exact <- get_hist_plot_comparisons(samp_dt, test_labels="exact", 
                                              param_types="par", itr_start=burn_in_start)
corr_plots_exact <- get_mcmc_2d_density_plots(samp_dt, test_labels="exact", 
                                              itr_start=burn_in_start)$exact

for(plt in trace_plots_exact) plot(plt) 
for(plt in hist_plots_exact) plot(plt)
for(plt in corr_plots_exact) plot(plt)
```

# Emulator Summary and Validation

```{r}
#
# Summarize GP fits.  
#

load(file.path(output_dir, "llik_em_list.RData"))
load(file.path(output_dir, "emulator_pred_list.RData"))
load(file.path(output_dir, "test_info.RData"))
em_names <- names(llik_em_list)

for(em_name in em_names) {
  print(em_name)
  cat(llik_em_list[[em_name]]$emulator_model$summarize(), "\n")
}
```

```{r}
# Log-likelihood emulator predictions at test points. 

for(em_name in em_names) {
  plt <- llik_em_list[[em_name]]$plot_pred_validation(test_info$input, true_llik=test_info$llik, 
                                                      emulator_pred_list=emulator_pred_list[[em_name]], 
                                                      plot_type="llik", include_interval=TRUE, 
                                                      interval_method=interval_method, N_std_dev=N_std_dev, 
                                                      plot_title=paste0("llik predictions: ", em_name))
  plot(plt)
}
```

```{r}
# Plot 1d projections: log-likelihood emulator distribution  

N_test_proj <- 100L
input_list_proj <- list()
for(par_name in inv_prob$par_names) {
  prior_bounds <- c(inv_prob$par_prior[par_name,"param1"], 
                    inv_prob$par_prior[par_name,"param2"])
  input_list_proj[[par_name]] <- seq(prior_bounds[1], prior_bounds[2], length.out=N_test_proj)
}

# Plot 1d projections. 
llik_func_true <- function(par) llik_exact$assemble_llik(par)
for(em_name in names(llik_em_list)) {
  plts <- llik_em_list[[em_name]]$plot_1d_projection(input_list_proj=input_list_proj,
                                                     include_design=FALSE, plot_title=em_name,
                                                     interval_method=interval_method, 
                                                     N_std_dev=N_std_dev, 
                                                     llik_func_true=llik_func_true)
  for(plt in plts) plot(plt)
}
```

```{r}
# Focus on single paramter. 
par_name <- "tauV"

for(i in random_idx) {
  for(em_name in names(llik_em_list)) {
    plts <- llik_em_list[[em_name]]$plot_1d_projection(input_list_proj=input_list_proj[par_name],
                                                       input_names_proj=par_name,
                                                       input_fixed=test_info$input[i,,drop=FALSE],
                                                       include_design=FALSE, plot_title=em_name,
                                                       interval_method=interval_method, 
                                                       N_std_dev=N_std_dev, 
                                                       llik_func_true=llik_func_true)
    plot(plts[[par_name]])
  }
}

```


```{r}
# Plot 1d projections: deterministic likelihood approximations. 

approx_types <- c("mean") #, "marginal")

for(em_name in names(llik_em_list)) {
  plts <- llik_em_list[[em_name]]$plot_1d_projection(input_list_proj=input_list_proj, 
                                                     plot_type="lik_approx", 
                                                     approx_types=approx_types,
                                                     llik_func_true=llik_func_true, 
                                                     include_design=FALSE, plot_title=em_name)
  for(plt in plts) plot(plt)
}
```

```{r}
# Focus on single paramter. 
par_name <- "tauV"

for(i in random_idx) {
  for(em_name in names(llik_em_list)) {
    plts <- llik_em_list[[em_name]]$plot_1d_projection(input_list_proj=input_list_proj[par_name],
                                                       input_names_proj=par_name,
                                                       plot_type="lik_approx", 
                                                       approx_types=approx_types,
                                                       input_fixed=test_info$input[i,,drop=FALSE],
                                                       include_design=FALSE, plot_title=em_name,
                                                       interval_method=interval_method, 
                                                       N_std_dev=N_std_dev, 
                                                       llik_func_true=llik_func_true)
    plot(plts[[par_name]])
  }
}

```

# GP-Induced Approximate Posterior Samples

```{r}
#
# MCMC Trace Plots: approximate. 
#

test_labels_approx <- setdiff(unique(samp_dt$test_label), "exact")
trace_plots_approx <- get_trace_plots(samp_dt[itr <= 2000],
                                      test_label=test_labels_approx,
                                      param_types="par",
                                      burn_in_start=burn_in_start)

for(plt in trace_plots_approx) plot(plt) 
```

```{r}
test_plts <- get_hist_plot_comparisons(samp_dt, burn_in_start=burn_in_start, 
                                       param_types="par", param_names="tauV",
                                       test_labels=test_labels_approx,
                                       test_label_baseline="exact")

for(plt in test_plts) plot(plt)
```


```{r}
# TODO: `get_1d_kde_plot_comparisons` seems to have a bug that causes the plots 
# to be off when `param_names` contains more than one name. Need to figure out 
# what's going on here. 

test_labels_noisy <- c("mcwmh-joint-em_llik_const_GaussQuad", 
                       "mcwmh-ind-em_llik_const_GaussQuad")

for(par_name in inv_prob$par_names) {
  kde_plts <- get_1d_kde_plot_comparisons(samp_dt, burn_in_start=burn_in_start, 
                                          param_types="par", param_names=par_name,
                                          test_label_baseline="exact",
                                          test_labels=test_labels_noisy, bandwidth_mult=2.0,
                                          xlab="parameter", ylab="kde", save_dir=NULL) 
  plot(kde_plts[[1]])
}

# for(plt in kde_plts) plot(plt)
```

```{r}
# mcmc_par_stats <- compute_mcmc_param_stats(samp_dt, burn_in_start=burn_in_start, 
#                                            test_labels=NULL, param_types="par")
#                          
# mcmc_errs_list <- compute_mcmc_comparison_metrics(samp_dt, "exact", "marg-fwd", c("mean", "cov"), 
#                                                   burn_in_start=burn_in_start, param_types="par")
                                                  

```


```{r}
# TODO: should linearly scale all of theses so that the parameters are on the 
# same scale, and the magnitude of their errors can be compared. 

scatter_stat_plts <- get_mcmc_moments_scatter_plot_comparisons(samp_dt, test_label_baseline="exact",
                                                               burn_in_start=burn_in_start, param_types="par")

for(plt in scatter_stat_plts) plot(plt)
```

```{r}
coverage_plt_list <- get_1d_coverage_plots(samp_dt, "exact", burn_in_start=burn_in_start,
                                           param_types="par", probs=seq(.1, .99, .05))
coverage_plts <- coverage_plt_list$plots

for(plt in coverage_plts) plot(plt)
```









